[tool.poetry]
name = "pyo3_decimal"
version = "0.1.0"
description = "Decimal implemnted with PyO3."
authors = ["fx kirin <fx.kirin@gmail.com>"]

[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]
