[tool.poetry]
name = "pyo3_decimal_user"
version = "0.1.0"
description = "pyo3_decimal usage example."
authors = ["fx kirin <fx.kirin@gmail.com>"]

[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]
